### ISSUE TITLE
Unclean shutdown on Ctrl-C

### ISSUE THREAD

**Issue by zgoda** [richardsheridan/trio-parallel#34]
If my code calls any sync function in parallel, i'm getting stack trace printed in terminal upon exiting program with Ctrl-C:

```
^CProcess trio-parallel worker process 0:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jazg/work/chitty/venv/lib/python3.9/site-packages/trio_parallel/_proc.py", line 61, in _work
    barrier.wait(timeout=IDLE_TIMEOUT)
  File "/usr/lib/python3.9/threading.py", line 635, in wait
    self._wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 670, in _wait
    if not self._cond.wait_for(lambda : self._state != 0, timeout):
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 313, in wait_for
    self.wait(waittime)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
```

Python 3.9.2 on Ubuntu 20.04
Trio 0.18, trio-parallel 0.3

**Comment by richardsheridan** [comment]
Hi, thanks for filing this issue! This should not happen of course. The more strange thing is that your exact system is in my CI matrix, so it should really work.  I am working on a 0.4 release, and I have fixed some synchronization bugs since 0.3. Could you try your code using an install from the `trio-parallel` `main` branch?

**Comment by zgoda** [comment]
Unfortunately this did not change anything.

The exact code where trio-parallel is used is https://github.com/zgoda/chitty-server/blob/f34c97885a8d6f470bbb6103d3cdaff384e162fb/src/chitty/web.py, lines 28 and 32. The stacktrace appears only if this code was executed otherwise shuts down cleanly.

I noticed also leaking semaphores if hypercorn is running with reloader, but I suppose this is to be expected.

**Comment by richardsheridan** [comment]
Is that a private repository? I'm getting a 404 when I click. Since I can't see for myself, I will just ask: Are you using hypercorn and quart-trio? Are you using a graceful shutdown? Is the specific usage of `trio_parallel.run_sync` cancellable? I'm a little surprised to see the `KeyboardInterrupt` appear in the child processes, as I thought Trio should intercept that signal.

Also I would like to get a handle on that semaphore leak if you can reproduce it without involving hypercorn.

**Comment by zgoda** [comment]
Ah, I'm sorry, I forgot about that. Made it public.

That semaphore leak is reported only if hypercorn is running with reloader. To trigger it from the code in the repo run it with `--debug`, this enables hypercorn reloader - it's not very smart so `touch`'ing `web.py` is enough to trigger reload. You will need some Redis also. After every request to any of these 2 endpoints that I mentioned earlier one semaphore seems to leak.
