### ISSUE TITLE
hint about systemd subprocess termination

### ISSUE THREAD

**Issue by belm0** [richardsheridan/trio-parallel#348]
A colleague discovered that the default systemd KillMode (`control-group`) will kill subprocesses indiscriminately.  Change it to `mixed` for SIGTERM of main, followed by SIGKILL of subprocesses after a timeout.

  https://www.freedesktop.org/software/systemd/man/systemd.kill.html

This was causing `BrokenWorkerProcessError: ('Graceful shutdown failed:  ...') errors from trio-parallel in shutdown.

Please consider adding a hint to the documentation, for systemd users.

**Comment by richardsheridan** [comment]
Thanks for the suggestion! I guess this is one of the painful burdens of strictly checking every reaped process's status code. 

Reading the link there it does seem like `mixed` is the right setting for trio services or any structured concurrent systems with subprocesses for that matter.

I did have a similar situation back in #34, which I fixed by setting the python signal handler for `SIGINT` to `SIG_IGN`. Since then I've been thinking about doing the same for `SIGTERM`, but since I don't have any application for it day to day I wasn't sure if it would be too heavy-handed. But it seems like it would've precisely prevented the default systemd settings from generating that error. Do you have any thoughts about "fixing" this issue in that way?

**Comment by belm0** [comment]
Hmm-- I guess anyone using systemctl should learn its quirks and sharp edges (defaulting to indiscriminate process tree kill being one of them), since it could apply to all manner of services.  Patching up everything in the universe that cares about graceful process tree shutdown isn't too attractive.

**Comment by belm0** [comment]
On the other hand, systemd isn't going to know the proper timeout to use for child processes (and there may not be only one answer for an app).  Ignoring the signal allows each child to be configured by the application itself.

**Comment by belm0** [comment]
Another systemd gotcha: it's important for services to start via `exec`.  Otherwise, I believe `sh` is used, which has its own handling about propagating SIGTERM to child processes.

**Comment by richardsheridan** [comment]
I revived my CI so I've written a paragraph about this in the docs in #359. I tried to make it more general than instructions on using systemd, but I did link back to this issue. Any comments you may have on the text would be welcome!
